application: drive-music-player
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index.html
  
- url: /icon_128\.png
  static_files: cws/icon_128.png
  upload: cws/icon_128.png
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /skin
  static_dir: skin
  
- url: /css
  static_dir: css